{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fullname" . }}-metrics-allow-prometheus
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  podSelector:
    matchLabels:
      app: {{ include "name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: {{ .Values.service.port | default 8002 }}
{{- end }}